// Client-only analytics helpers. Used from module scripts inside Astro components.
// The boot shim in AnalyticsBoot.astro defines window.etus + window.dataLayer.
// Server submission flows through window.etus.track/identify (auto-queue) + flush.

export type QuizBase = {
  quiz_slug: string;
  vertical: string;
  mode: string;
};

export function nowMs(): number {
  return Date.now();
}

export function quizBaseFromDom(root: HTMLElement | null): QuizBase {
  return {
    quiz_slug: root?.dataset.quizSlug ?? '',
    vertical: root?.dataset.quizVertical ?? '',
    mode: root?.dataset.quizMode ?? '',
  };
}

export function validityToErrorCode(v: ValidityState): string {
  if (v.valueMissing) return 'value_missing';
  if (v.typeMismatch) return 'type_mismatch';
  if (v.patternMismatch) return 'pattern_mismatch';
  if (v.tooShort) return 'too_short';
  if (v.tooLong) return 'too_long';
  if (v.rangeUnderflow) return 'range_underflow';
  if (v.rangeOverflow) return 'range_overflow';
  if (v.stepMismatch) return 'step_mismatch';
  if (v.badInput) return 'bad_input';
  if (v.customError) return 'custom_error';
  return 'unknown';
}

export function readSessionAnswers(): Record<string, string> {
  try {
    return JSON.parse(sessionStorage.getItem('quiz:answers') ?? '{}');
  } catch {
    return {};
  }
}

/**
 * Build the rich quiz_form_submitted track payload + identify traits and
 * push through the boot's unified queue (window.etus.track + identify),
 * then flush immediately so the events land at /v1/e before the user
 * navigates to /processing.
 *
 * The track event must carry:
 *   - properties.form.{email,phone,name,website}  → worker anti-fraud gates
 *     (T0.10 honeypot, T0.11 time gate via time_on_form_ms);
 *     worker hashes email/phone/name for AE + CAPI fan-out.
 *   - properties.turnstile_token  → worker verifies via siteverify (T0.8).
 *   - properties.time_on_form_ms  → T0.11 dwell gate.
 *   - quiz context (quiz_slug, vertical, mode), answers, consent, attribution.
 *
 * The identify event carries raw email/phone/name in traits — worker hashes.
 * Same `event_id` is generated by track() and used as the dedup key for any
 * downstream Pixel + CAPI matching (T1.12).
 */
export function submitLead(args: {
  lead: Record<string, FormDataEntryValue>;
  quizBase: QuizBase;
  consentGiven: boolean;
  /** Form-specific timing/flag properties from the submit handler. */
  formProperties: Record<string, unknown>;
}): { event_id: string } | undefined {
  const etus = window.etus;
  if (!etus || !etus.track || !etus.identify || !etus.flush) return undefined;

  const traits: Record<string, string> = {};
  if (typeof args.lead.email === 'string' && args.lead.email) traits.email = args.lead.email;
  if (typeof args.lead.phone === 'string' && args.lead.phone) traits.phone = args.lead.phone;
  if (typeof args.lead.name === 'string' && args.lead.name) traits.name = args.lead.name;

  // Identify first — gives the worker a chance to attach hashed PII to the
  // session record before the track event is processed.
  etus.identify(traits);

  // Rich track event. Worker reads form.website (honeypot), time_on_form_ms,
  // and turnstile_token from properties for anti-fraud. event_id auto-generated
  // and matches what was already in dataLayer for the same call.
  const formField = {
    email: typeof args.lead.email === 'string' ? args.lead.email : '',
    phone: typeof args.lead.phone === 'string' ? args.lead.phone : '',
    name: typeof args.lead.name === 'string' ? args.lead.name : '',
    website: typeof args.lead.website === 'string' ? args.lead.website : '',
  };
  const turnstileToken =
    typeof args.lead.turnstile_token === 'string' ? args.lead.turnstile_token : '';

  const trackPayload = etus.track('quiz_form_submitted', {
    ...args.quizBase,
    ...args.formProperties,
    answers: readSessionAnswers(),
    consent_given: args.consentGiven,
    form: formField,
    turnstile_token: turnstileToken,
    attribution: etus.attribution?.() ?? null,
  });

  // Force flush both queued events before the page navigates.
  etus.flush();

  return trackPayload ? { event_id: trackPayload.event_id } : undefined;
}
